### ISSUE TITLE
'session-run' still in clojure-tensorflow/save.clj 

### ISSUE THREAD

**Issue by ghost** [kieranbrowne/clojure-tensorflow#2]
Hi, 

Thanks for developing this very useful library.
I was using 0.1.6 and just tried to download 0.2.1 from clojars, however encountered the following error message.

Error:
java.lang.IllegalAccessError: session-run does not exist
  clojure.lang.ExceptionInfo: session-run does not exist
    file: "clojure_tensorflow/save.clj"
    line: 1
----------------------
It looks 'session-run' is still in save.clj even though it is not in core.clj.
It would be helpful to fix when you have a moment.

**Comment by kieranbrowne** [comment]
Hi @myst3m,
Thanks for submitting the issue. @atroche just patched it. Use [0.2.2](https://clojars.org/clojure-tensorflow/versions/0.2.2). :)

**Comment by ghost** [comment]
Hi,
Thanks so quickly !
